// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvVvuT0FnAXI8dLhYB4oZ6VlotqMASx8',
    appId: '1:1020331084162:web:d73ddddd9df47b5a8c679b',
    messagingSenderId: '1020331084162',
    projectId: 'campus-life-hub-cd39e',
    authDomain: 'campus-life-hub-cd39e.firebaseapp.com',
    storageBucket: 'campus-life-hub-cd39e.firebasestorage.app',
    measurementId: 'G-RCKFBV3LDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUi_noDfJ05Je8S1gml2QT9wW2ABmAos',
    appId: '1:1020331084162:android:a1ba94536749f98f8c679b',
    messagingSenderId: '1020331084162',
    projectId: 'campus-life-hub-cd39e',
    storageBucket: 'campus-life-hub-cd39e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVY-m3aL4XrbzMA9GJMPL9Gaa3jI9Gyc',
    appId: '1:1020331084162:ios:7868cfa2eb1ef55d8c679b',
    messagingSenderId: '1020331084162',
    projectId: 'campus-life-hub-cd39e',
    storageBucket: 'campus-life-hub-cd39e.firebasestorage.app',
    iosBundleId: 'com.example.campusLifeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVY-m3aL4XrbzMA9GJMPL9Gaa3jI9Gyc',
    appId: '1:1020331084162:ios:7868cfa2eb1ef55d8c679b',
    messagingSenderId: '1020331084162',
    projectId: 'campus-life-hub-cd39e',
    storageBucket: 'campus-life-hub-cd39e.firebasestorage.app',
    iosBundleId: 'com.example.campusLifeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARvVvuT0FnAXI8dLhYB4oZ6VlotqMASx8',
    appId: '1:1020331084162:web:763ac5a357ab42cd8c679b',
    messagingSenderId: '1020331084162',
    projectId: 'campus-life-hub-cd39e',
    authDomain: 'campus-life-hub-cd39e.firebaseapp.com',
    storageBucket: 'campus-life-hub-cd39e.firebasestorage.app',
    measurementId: 'G-LGT3KJK7EB',
  );

}